### ISSUE TITLE
钱包可用余额少于0.03提取分红失败

### ISSUE THREAD

**Issue by cjy37** [eosforce/wallet-desktop#81]
EOSForce钱包 1.0.1
可用余额少于 0.03 EOS
提取分红时报错：
```
code: 10
false: on fee transaction failed, but
shouldn't enough asset to pay for
transaction fee
```

希望手续费可以从提取分红中扣除，
否则，好像我现在什么都不能操作了，
不能赎回投票，也不能提取分红

**Comment by cjy37** [comment]
![qq 20180708173204](https://user-images.githubusercontent.com/4444496/42418618-d429a23a-82d6-11e8-84f8-78d9e6eb8cc7.png)

**Comment by cjy37** [comment]
@eosforce

**Comment by muhazir99** [comment]
K

**Comment by fanyang1988** [comment]
@cjy37 扣除手续费的过程由eosforce实现决定，目前eosforce通过一个内部的transaction来先完成扣除手续费，之后执行action，如果改为手续费从分红中扣除会影响所有的手续费逻辑。

**Comment by cjy37** [comment]
eosforce实现，在哪里反馈问题？帐号金额少于0.03又不能充值，这是要等死的节奏吧

**Comment by fanyang1988** [comment]
@cjy37 提给 github.com/eosforce/eosforce
